"""Turning the fitted Gaussian into something Cobaya can use.

Three formats:

``json``    mu, Sigma, its Cholesky factor, the exponents of Eq. (23) and the
            sampling box -- for any other code.
``cobaya``  a ready-to-paste YAML fragment: a ``params`` block that samples in
            the Gaussianised basis {X1..X4} with EFTCAMB's own parameter names
            derived from it, plus the ``likelihood`` entry for the plugin.
``covmat``  a Cobaya proposal covariance in the X basis, so ``learn_proposal``
            does not have to rediscover the correlations from scratch.

The ``cobaya`` snippet samples in X (the paper's choice, Sec. VI, and the basis
in which the distribution is actually Gaussian) and maps back with Cobaya's
``drop``/``value`` mechanism, so EFTCAMB still receives
``Shift_Symmetric_alphaB0``, ``Shift_Symmetric_m``, ``EFTw0`` and ``EFTwa``.
"""

from __future__ import annotations

import json
import os
from typing import List, Optional

import numpy as np

__all__ = ["export_prior", "cobaya_snippet"]


def cobaya_snippet(prior, plugin_path: str, prior_file: str) -> str:
    p = prior.exponents
    p2, p3, p4 = p["p2"], p["p3"], p["p4"]
    r = prior.x_ranges or {}

    def rng(name, default):
        lo, hi = r.get(name, default)
        return float(lo), float(hi)

    x1 = rng("X1", (0.0, 10.0))
    x2 = rng("X2", (0.0, 15.0))
    x3 = rng("X3", (-10.0, 0.0))
    x4 = rng("X4", (-15.0, 30.0))
    sd = np.sqrt(np.diag(prior.cov))
    mu = prior.mu

    m_expr = f"X2 / X1**({p2!r})"
    lines = [
        "# --- theoretical prior on shift-symmetric Horndeski -------------------",
        "# Generated by `ssprior export --format cobaya`.",
        "# Samples in the Gaussianised basis {X1..X4} of Eq. (23), where the",
        "# theoretical prior is a multivariate normal, and maps back to the",
        "# parameter names EFTCAMB expects.  'ref' and 'proposal' come from the",
        "# fitted mu and sqrt(diag(Sigma)).",
        "# X1..X4 are deliberately not 'drop'ped: ss_theory_prior requires them,",
        "# and Cobaya never assigns a dropped parameter to a component.",
        "params:",
    ]
    for nm, (lo, hi), m_i, s_i in zip(("X1", "X2", "X3", "X4"), (x1, x2, x3, x4), mu, sd):
        lines += [
            f"  {nm}:",
            f"    prior: {{min: {lo:g}, max: {hi:g}}}",
            f"    ref: {{dist: norm, loc: {m_i:.6f}, scale: {s_i:.6f}}}",
            f"    proposal: {s_i:.6f}",
            f"    latex: X_{nm[-1]}",
        ]
    lines += [
        "  Shift_Symmetric_alphaB0:",
        "    value: 'lambda X1: X1'",
        "    latex: \\hat{\\alpha}_{\\rm B}",
        "  Shift_Symmetric_m:",
        f"    value: 'lambda X1, X2: {m_expr}'",
        "    latex: m",
        "  EFTw0:",
        f"    value: 'lambda X1, X2, X3: X3 / ({m_expr})**({p3!r})'",
        "    latex: w_0",
        "  EFTwa:",
        f"    value: 'lambda X1, X2, X4: X4 / ({m_expr})**({p4!r})'",
        "    latex: w_a",
        "",
        "likelihood:",
        "  ss_theory_prior.SSTheoryPrior:",
        f"    python_path: {plugin_path}",
        f"    prior_file: {prior_file}",
        "    basis: X",
    ]
    if prior.alphaB_convention_factor is None:
        lines += [
            "",
            "# NOTE: alphaB_convention_factor is not calibrated in this prior file.",
            "# Run `ssprior eftcamb-check --kind growth --calibrate` and confirm the",
            "# factor is 1 before trusting Shift_Symmetric_alphaB0 = X1 literally:",
            "# EFTCAMB stores alpha_B in the RPH basis and the relation to the",
            "# Bellini-Sawicki alpha_B used by the paper is not documented in the",
            "# Fortran source.",
        ]
    return "\n".join(lines) + "\n"


def export_prior(prior, fmt: str, output: Optional[str], plugin_path: Optional[str],
                 prior_file: str) -> List[str]:
    base = output or os.path.splitext(prior_file)[0]
    written: List[str] = []

    if fmt == "json":
        # NOT "<base>.json": that is the .npz's own sidecar, which holds the
        # exponents and the basis names.  Writing there would silently destroy
        # the metadata that GaussianPrior.load needs.
        path = base + "_export.json" if not base.endswith(".json") else base
        chol = np.linalg.cholesky(prior.cov)
        payload = {
            "name": prior.name, "x_names": prior.x_names,
            "mu": prior.mu.tolist(), "cov": prior.cov.tolist(),
            "cholesky": chol.tolist(), "inv_cov": prior.inv_cov.tolist(),
            "exponents": prior.exponents, "x_ranges": prior.x_ranges,
            "n_samples": prior.n_samples,
            "alphaB_convention_factor": prior.alphaB_convention_factor,
            "transform": "X1 = aB; X2 = m aB^p2; X3 = w0 m^p3; X4 = wa m^p4",
        }
        with open(path, "w") as fh:
            json.dump(payload, fh, indent=2)
        written.append(path)

    elif fmt == "cobaya":
        path = base + "_cobaya.yaml" if not base.endswith(".yaml") else base
        pp = plugin_path or os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "cobaya_plugins")
        with open(path, "w") as fh:
            fh.write(cobaya_snippet(prior, pp, prior_file))
        written.append(path)

    elif fmt == "covmat":
        path = base + ".covmat" if not base.endswith(".covmat") else base
        with open(path, "w") as fh:
            fh.write("# " + " ".join(prior.x_names) + "\n")
            for row in prior.cov:
                fh.write(" ".join(f"{v: .8e}" for v in row) + "\n")
        written.append(path)

    else:
        raise ValueError(f"unknown format {fmt!r}")

    return written
